#!/usr/bin/python3

import jetson.inference
import jetson.utils

import argparse
from random import randrange

# parse the command line
parser = argparse.ArgumentParser()
parser.add_argument("filename", type=str, help="filename of the image to process")
parser.add_argument("--network", type=str, default="googlenet", help="model to use, can be:  googlenet, resnet-18, ect.")
args = parser.parse_args()

# load an image (into shared CPU/GPU memory)
img = jetson.utils.loadImage(args.filename)

# load the recognition network
net = jetson.inference.imageNet(args.network)

# classify the image
class_idx, confidence = net.Classify(img)

# find the object description
class_desc = net.GetClassDesc(class_idx).lower().split(', ')

# print out the result
clothingList = {"jean": randrange(40, 50),
                "t-shirt": randrange(20, 30),
                "jacket": randrange(30, 40),
                "shoes": randrange(50, 60),
                "shirt": randrange(15, 25)}



print("image is recognized as '{}' (class #{:d}) with {:f}% confidence".format(class_desc, class_idx, confidence * 100))



for item in class_desc:
    itemValue = clothingList.get(item, 0)
    if itemValue == 0:
        continue
    itemValue = str(itemValue)
    print("The cost of this " + item + " is $" + itemValue)
